/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-05-06 08:44:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import member.*;
import java.text.*;

public final class memberInfoForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("member");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원가입폼</title>\r\n");
      out.write("<style>\r\n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Paytone+One&display=swap');\r\n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap');\r\n");
      out.write("\r\n");
      out.write("#container {\r\n");
      out.write("	width: 500px;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: black;	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span {\r\n");
      out.write("	font-size: 0.8em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"text\"], input[type=\"password\"] {\r\n");
      out.write("	height: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 상단 - 메인, 서브 타이틀 */\r\n");
      out.write(".m_title {\r\n");
      out.write("	font-family: 'Paytone One', sans-serif;\r\n");
      out.write("	font-size: 3em;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".s_title {\r\n");
      out.write("	font-family: 'Do Hyeon', sans-serif;\r\n");
      out.write("	font-size: 2em;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margint-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 중단 - 입력 테이블 */\r\n");
      out.write("table {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	border: 1px solid black;\r\n");
      out.write("	border-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr {\r\n");
      out.write("	height: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th, td {\r\n");
      out.write("	border: 1px solid black;\r\n");
      out.write("	padding-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("	background-color: #ced4da;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".c_id {\r\n");
      out.write("	background-color: #ccc;	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".s_id {\r\n");
      out.write("	color: red;\r\n");
      out.write("	font-size: 0.9em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".addr_row {\r\n");
      out.write("	height: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".addr_row input {\r\n");
      out.write("	margin: 2px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".address:focus {\r\n");
      out.write("	outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".c_id:focus {\r\n");
      out.write("	outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btn_address {\r\n");
      out.write("	width: 100px;\r\n");
      out.write("	height: 28px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	background-color: #2f9277;\r\n");
      out.write("	color: white;\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	border-radius: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 하단 - 가입, 취소 버튼  */\r\n");
      out.write(".btns {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btns input[type=\"button\"] {\r\n");
      out.write("	width: 120px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	background-color: black;\r\n");
      out.write("	color: white;\r\n");
      out.write("	border: none;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("	document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("		let form = document.infoForm; // 폼은 그냥 받을 수 있음\r\n");
      out.write("		let id = form.id;\r\n");
      out.write("		let pwd = form.pwd;\r\n");
      out.write("		let pwd2 = form.pwd2;\r\n");
      out.write("		let name = form.name;\r\n");
      out.write("		let email = form.email;\r\n");
      out.write("		let tel = form.tel;\r\n");
      out.write("		let address = form.address;\r\n");
      out.write("		let address2 = form.address2;\r\n");
      out.write("		\r\n");
      out.write("		// 비밀번호 - pwd\r\n");
      out.write("		// 비밀번호(pwd) 유효성 검사 - 4글자 이상의 비밀번호를 생성하도록 함\r\n");
      out.write("		let chk_pwd = document.getElementById(\"chk_pwd\");\r\n");
      out.write("		pwd.addEventListener(\"keyup\", function() {\r\n");
      out.write("			if (pwd.value.length < 4) {\r\n");
      out.write("				chk_pwd.innerHTML = \"비밀번호는 4글자 이상이어야 합니다.\";\r\n");
      out.write("				chk_pwd.style.color = \"red\";\r\n");
      out.write("			} else {\r\n");
      out.write("				chk_pwd.innerHTML = \"사용 가능한 비밀번호입니다.\"\r\n");
      out.write("				chk_pwd.style.color = \"blue\";\r\n");
      out.write("			}	\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("		// 비밀번호 확인(pwd2)과 비밀번호의 내용이 동일한지 유무 판단\r\n");
      out.write("		let chk_pwd2 = document.getElementById(\"chk_pwd2\");\r\n");
      out.write("		pwd2.addEventListener(\"keyup\", function() {\r\n");
      out.write("			if (pwd.value == pwd2.value) {\r\n");
      out.write("				chk_pwd2.innerHTML = \"비밀번호가 일치합니다.\"\r\n");
      out.write("				chk_pwd2.style.color = \"blue\";\r\n");
      out.write("			} else {\r\n");
      out.write("				chk_pwd2.innerHTML = \"비밀번호가 일치하지 않습니다.\"\r\n");
      out.write("				chk_pwd2.style.color = \"red\";\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("		// 이메일 검사 함수\r\n");
      out.write("		let isEmail = function(value) {\r\n");
      out.write("			return (value.indexOf('@') > 1) && (value.split('@')[1].indexOf('.') > 2)\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		// 이메일 확인\r\n");
      out.write("		// 1. '@' 문자를 포함하고 있는지의 여부 -> 아이디가 3글자 이상인지 판별\r\n");
      out.write("		// 2. '@'문자 다음에 '.'을 포함하고 있는지의 여부 -> 회사 이름도 3글자 이상인지를 판별\r\n");
      out.write("		let chk_email = document.getElementById(\"chk_email\");\r\n");
      out.write("		email.addEventListener(\"keyup\", function(event) {\r\n");
      out.write("			let value = event.currentTarget.value;\r\n");
      out.write("			if (isEmail(value)){\r\n");
      out.write("				// 이메일 형식이 맞을 때	\r\n");
      out.write("				chk_email.innerText = \"이메일 형식입니다. : \" + value;\r\n");
      out.write("				chk_email.style.color = \"green\";\r\n");
      out.write("			} else {\r\n");
      out.write("				// 이메일 형식이 아닐 때\r\n");
      out.write("				chk_email.innerText = \"이메일 형식이 아닙니다. : \" + value;\r\n");
      out.write("				chk_email.style.color = \"red\";\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("		// 주소 찾기 버튼 - 다음 라이브러리 활용\r\n");
      out.write("		let btn_address = document.getElementById(\"btn_address\");\r\n");
      out.write("		btn_address.addEventListener(\"click\", function() {\r\n");
      out.write("			new daum.Postcode({\r\n");
      out.write("				oncomplete:function(data) {\r\n");
      out.write("					address.value = data.address;\r\n");
      out.write("				}	\r\n");
      out.write("			}).open();	\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("		// 회원정보 수정 버튼을 클릭할 때\r\n");
      out.write("		// 회원정보 수정 페이지의 전체 내용 입력 유무에 따른 유효성 검사와 페이지 이동 처리\r\n");
      out.write("		let btn_update = document.getElementById(\"btn_update\");\r\n");
      out.write("		btn_update.addEventListener(\"click\", function() {\r\n");
      out.write("			if (pwd.value.length == 0) {\r\n");
      out.write("				// 비밀번호를 입력하지 않았을 때\r\n");
      out.write("				alert('비밀번호를 입력하시오!');\r\n");
      out.write("				pwd.focus();\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			if (pwd2.value.length == 0) {\r\n");
      out.write("				// 비밀번호 확인을 입력하지 않았을 때\r\n");
      out.write("				alert('비밀번호 확인을 입력하시오!');\r\n");
      out.write("				pwd2.focus();\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			if (pwd.value != pwd2.value) {\r\n");
      out.write("				alert('비밀번호 확인이 비밀번호와 다릅니다.');\r\n");
      out.write("				pwd2.focus();\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			if (name.value.length == 0) {\r\n");
      out.write("				// 이름을 입력하지 않았을 때\r\n");
      out.write("				alert('이름을 입력하시오!');\r\n");
      out.write("				name.focus();\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			if (email.value.length == 0) {\r\n");
      out.write("				// 이메일을 입력하지 않았을 때\r\n");
      out.write("				alert('이메일을 입력하시오!');\r\n");
      out.write("				email.focus();\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			if (tel.value.length == 0) {\r\n");
      out.write("				// 전화번호를 입력하지 않았을 때\r\n");
      out.write("				alert('전화번호를 입력하시오!');\r\n");
      out.write("				tel.focus();\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			if (address.value.length == 0) {\r\n");
      out.write("				// 주소를 입력하지 않았을 때\r\n");
      out.write("				alert('주소를 입력하시오!');\r\n");
      out.write("				address.focus();\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			form.submit(); // 최종적으로 전송\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		// 회원 탈퇴 버튼을 클릭할 때 \r\n");
      out.write("		// 회원 삭제\r\n");
      out.write("		let btn_delete = document.getElementById(\"btn_delete\");\r\n");
      out.write("		btn_delete.addEventListener(\"click\", function() {\r\n");
      out.write("			let form = document.infoForm;\r\n");
      out.write("			\r\n");
      out.write("			if(!form.id.value) {\r\n");
      out.write("				alert('아이디를 입력하시오.');\r\n");
      out.write("				form.id.focus();\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			if(!form.pwd.value) {\r\n");
      out.write("				alert('비밀번호를 입력하시오.');\r\n");
      out.write("				form.pwd.focus();\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			if(!form.pwd2.value) {\r\n");
      out.write("				alert('비밀번호 확인을 입력하시오.');\r\n");
      out.write("				form.pwd2.focus();\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			if(pwd.value != pwd2.value) {\r\n");
      out.write("				alert('비밀번호를 올바르게 입력하시오.');\r\n");
      out.write("				form.pwd2.focus();\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			let answer = confirm('정말 회원을 탈퇴하겠습니까?')\r\n");
      out.write("			\r\n");
      out.write("			if (answer) {\r\n");
      out.write("				form.action = 'memberDeletePro.jsp'; // 폼의 액션 변경\r\n");
      out.write("				form.submit();\r\n");
      out.write("			} else {\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("	})\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");


String memberId = (String)session.getAttribute("memberId");

if (memberId == null) {
	out.print("<script>location='../logon/memberLoginForm.jsp'</script>");
}

// 아래는 세션 memberId가 있을 때 실행
MemberDAO memberDAO = MemberDAO.getInstance();
MemberDTO member = new MemberDTO(); // memberDTO 인스턴스 생성
member = memberDAO.getMember(memberId); // 생성한 인스턴스에  

SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

      out.write("\r\n");
      out.write("	<div id=\"container\">\r\n");
      out.write("		<div class=\"m_title\">\r\n");
      out.write("			<a href=\"../board/boardList.jsp\">EZEN MALL</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"s_title\">회원 정보 확인</div>\r\n");
      out.write("\r\n");
      out.write("		<form action=\"memberUpdatePro.jsp\" method=\"post\" name=\"infoForm\">\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>아이디</th>\r\n");
      out.write("					<td><input type=\"text\" name=\"id\" size=\"15\" value=\"");
      out.print(member.getId());
      out.write("\" class=\"c_id\" readonly>\r\n");
      out.write("					&ensp; <span class=\"s_id\">아이디는 변경 불가</span> \r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>비밀번호</th>\r\n");
      out.write("					<td><input type=\"password\" name=\"pwd\" size=\"15\" value=\"");
      out.print(member.getPwd());
      out.write("\"><br>\r\n");
      out.write("						<span id=\"chk_pwd\"></span></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>비밀번호 확인</th>\r\n");
      out.write("					<td><input type=\"password\" name=\"pwd2\"><br> \r\n");
      out.write("					<span id=\"chk_pwd2\"></span></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>이름</th>\r\n");
      out.write("					<td><input type=\"text\" name=\"name\" size=\"15\" value=\"");
      out.print(member.getName());
      out.write("\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>이메일</th>\r\n");
      out.write("					<td><input type=\"text\" name=\"email\" size=\"30\" value=\"");
      out.print(member.getEmail());
      out.write("\"><br>\r\n");
      out.write("						<span id=chk_email></span>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>전화번호</th>\r\n");
      out.write("					<td><input type=\"text\" name=\"tel\" size=\"20\" value=\"");
      out.print(member.getTel());
      out.write("\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr class=\"addr_row\">\r\n");
      out.write("					<th>주소</th>\r\n");
      out.write("					<td>\r\n");
      out.write("						<input type=\"button\" value=\"주소찾기\" id=\"btn_address\"><br>\r\n");
      out.write("						<input type=\"text\" name=\"address\" size=\"49\" readonly class=\"address\"><br> \r\n");
      out.write("						<input type=\"text\" name=\"address2\" size=\"49\">\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>가입 일자</th>\r\n");
      out.write("					<td>\r\n");
      out.write("						");
      out.print(sdf.format(member.getRegDate()) );
      out.write("\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("			<div class=\"btns\">\r\n");
      out.write("				<input type=\"button\" value=\"회원정보수정\" id=\"btn_update\">&emsp;&emsp;\r\n");
      out.write("				<input type=\"button\" value=\"회원탈퇴\" id=\"btn_delete\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
